import Link from "next/link"
import { redirect } from "next/navigation"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

const cards=[{href:"/account/orders",icon:"□",title:"Orders",text:"Track purchases and delivery"},{href:"/account/profile",icon:"○",title:"Profile",text:"Name and email settings"},{href:"/account/addresses",icon:"⌂",title:"Addresses",text:"Manage delivery details"},{href:"/wishlist",icon:"♡",title:"Wishlist",text:"Saved pieces you love"}]
export default async function AccountPage(){
 const session=await getServerSession(authOptions); if(!session?.user?.id) redirect("/login?callbackUrl=/account")
 const [user,orderCount,wishlist]=await Promise.all([prisma.user.findUnique({where:{id:session.user.id},select:{name:true,email:true,createdAt:true}}),prisma.order.count({where:{userId:session.user.id}}),prisma.wishlist.findUnique({where:{userId:session.user.id},select:{_count:{select:{items:true}}}})])
 if(!user) redirect("/login")
 const recent=await prisma.order.findMany({where:{userId:session.user.id},orderBy:{createdAt:"desc"},take:3,select:{id:true,orderNumber:true,total:true,status:true,createdAt:true}})
 return <div className="min-h-screen bg-cream py-10"><div className="max-w-6xl mx-auto px-4"><div className="bg-charcoal text-white rounded-3xl p-7 md:p-10"><p className="text-xs uppercase tracking-[0.24em] text-white/60">NOORÉ member</p><h1 className="font-editorial text-4xl md:text-5xl mt-2">Welcome back, {user.name||"Customer"}.</h1><p className="text-white/65 mt-3">Your saved pieces, orders and delivery details — all in one place.</p></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-5"><div className="bg-white border border-cream rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-secondary">Orders</p><p className="text-3xl font-semibold mt-2">{orderCount}</p></div><div className="bg-white border border-cream rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-secondary">Wishlist</p><p className="text-3xl font-semibold mt-2">{wishlist?._count.items||0}</p></div><div className="bg-white border border-cream rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-secondary">Member since</p><p className="font-semibold mt-3">{new Date(user.createdAt).toLocaleDateString()}</p></div><div className="bg-white border border-cream rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-secondary">Email</p><p className="font-semibold mt-3 truncate">{user.email}</p></div></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8">{cards.map(card=><Link key={card.href} href={card.href} className="bg-white border border-cream rounded-2xl p-6 hover:-translate-y-0.5 hover:shadow-lg transition"><div className="text-3xl">{card.icon}</div><h2 className="font-semibold mt-5">{card.title}</h2><p className="text-sm text-secondary mt-1">{card.text}</p><span className="inline-block mt-5 text-sm font-medium">Open →</span></Link>)}</div>
 <section className="bg-white border border-cream rounded-2xl mt-8 p-6 md:p-8"><div className="flex justify-between items-center"><div><p className="text-xs uppercase tracking-wider text-secondary">Latest activity</p><h2 className="font-editorial text-2xl mt-1">Recent orders</h2></div><Link href="/account/orders" className="text-sm font-medium hover:underline">View all</Link></div>{recent.length===0?<p className="text-secondary mt-6">No purchases yet. <Link href="/products" className="text-charcoal underline">Explore the collection.</Link></p>:<div className="mt-5 divide-y divide-cream">{recent.map(order=><Link href={`/account/orders/${order.id}`} key={order.id} className="py-4 first:pt-0 last:pb-0 flex justify-between items-center gap-4"><div><p className="font-medium">#{order.orderNumber}</p><p className="text-xs text-secondary mt-1">{new Date(order.createdAt).toLocaleDateString()}</p></div><div className="text-right"><p className="font-semibold">PKR {order.total.toLocaleString()}</p><p className="text-xs text-secondary mt-1">{order.status.replaceAll("_"," ")}</p></div></Link>)}</div>}</section>
 </div></div>
}
