import { prisma } from "@/lib/prisma"
import Link from "next/link"

export default async function AdminInventoryPage() {
  const products = await prisma.product.findMany({ orderBy: { stock: "asc" }, where: { status: "ACTIVE" } })
  const lowStockProducts = products.filter(p => p.stock < 5)
  const outOfStockProducts = products.filter(p => p.stock === 0)
  const healthy = products.filter(p => p.stock >= 5).length
  return <div className="max-w-7xl pb-12">
    <header className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-secondary">NOORÉ / Stock control</p><h1 className="mt-2 font-editorial text-4xl md:text-5xl">Inventory</h1><p className="mt-2 max-w-2xl text-sm text-secondary">A clean operational view of available stock, risk items and inventory history.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/inventory/history" className="rounded-xl border border-charcoal/10 bg-white px-4 py-3 text-xs font-semibold uppercase tracking-[0.14em] shadow-sm transition hover:bg-charcoal/[0.03]">History</Link><a href="/api/admin/reports?type=inventory" className="rounded-xl bg-charcoal px-4 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-white shadow-lg">Export CSV</a></div></header>
    <div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Active products",products.length,""],["Healthy stock",healthy,""],["Low stock",lowStockProducts.length,"amber"],["Out of stock",outOfStockProducts.length,"red"]].map(([label,value,tone])=><div key={String(label)} className="rounded-2xl border border-charcoal/10 bg-white p-5 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-secondary">{label}</p><p className={`mt-2 text-3xl font-semibold ${tone==="red"?"text-red-600":tone==="amber"?"text-amber-600":""}`}>{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-3xl border border-charcoal/10 bg-white shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><div className="border-b border-charcoal/10 px-5 py-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-secondary">Stock ledger</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-charcoal/[0.035]"><tr>{["Product","SKU","Stock","Status","Action"].map(h=><th key={h} className="px-5 py-4 text-left text-[10px] font-semibold uppercase tracking-[0.16em] text-secondary">{h}</th>)}</tr></thead><tbody>{products.length===0?<tr><td colSpan={5} className="p-14 text-center"><p className="font-semibold">Inventory is empty</p><p className="mt-1 text-sm text-secondary">Active products will appear here when they are added.</p></td></tr>:products.map(product=>{const out=product.stock===0;const low=product.stock<5;return <tr key={product.id} className="border-t border-charcoal/10 transition hover:bg-charcoal/[0.02]"><td className="px-5 py-4 font-medium">{product.name}</td><td className="px-5 py-4 font-mono text-xs text-secondary">{product.sku}</td><td className={`px-5 py-4 text-lg font-semibold ${out?"text-red-600":low?"text-amber-600":""}`}>{product.stock}</td><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide ${out?"border-red-200 bg-red-50 text-red-700":low?"border-amber-200 bg-amber-50 text-amber-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{out?"Out of Stock":low?"Low Stock":"In Stock"}</span></td><td className="px-5 py-4"><Link href={`/admin/products/edit/${product.id}`} className="font-medium underline underline-offset-4">Update Stock</Link></td></tr>})}</tbody></table></div></section>
  </div>
}
