import { notFound } from "next/navigation"
import { prisma } from "@/lib/prisma"
export const dynamic="force-dynamic"
function money(v:number){return `PKR ${v.toLocaleString("en-PK")}`}
export default async function PrintOrderPage({params,searchParams}:{params:{id:string};searchParams?:{mode?:string}}){
 const order=await prisma.order.findUnique({where:{id:params.id},include:{user:{select:{name:true,email:true}},address:true,items:{include:{product:true,variant:true}}}});if(!order)notFound();
 const packing=searchParams?.mode==="packing"; const site="https://noore-slf5.vercel.app";
 return <main className="min-h-screen bg-[#f4f1eb] p-4 text-[#171717] print:bg-white print:p-0"><div className="mx-auto max-w-4xl overflow-hidden rounded-[28px] bg-white shadow-[0_20px_70px_rgba(23,23,23,.10)] print:max-w-none print:rounded-none print:shadow-none">
  <div className="relative overflow-hidden bg-[#171717] px-7 py-8 text-white md:px-10"><div className="absolute -right-16 -top-20 h-48 w-48 rounded-full border border-white/10"/><div className="relative flex items-start justify-between gap-6"><div className="flex items-center gap-4"><img src="/apple-touch-icon.png" alt="NOORÉ" className="h-14 w-14 rounded-2xl bg-white object-cover p-1"/><div><p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-white/55">NOORÉ</p><h1 className="mt-1 font-editorial text-3xl">{packing?"Packing Slip":"Order Invoice"}</h1><p className="mt-1 text-sm text-white/60">Thank you for choosing NOORÉ.</p></div></div><div className="text-right"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/50">Order</p><p className="mt-1 text-xl font-semibold">#{order.orderNumber}</p><p className="mt-1 text-xs text-white/60">{order.createdAt.toLocaleString("en-PK",{dateStyle:"medium",timeStyle:"short"})}</p></div></div></div>
  <div className="p-7 md:p-10"><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-black/10 bg-[#faf9f6] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-black/45">Customer</p><p className="mt-3 font-semibold">{order.user?.name||"Customer"}</p><p className="mt-1 text-sm text-black/65">{order.user?.email||""}</p><p className="mt-1 text-sm text-black/65">{order.address?.phone||""}</p></div><div className="rounded-2xl border border-black/10 bg-[#faf9f6] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-black/45">Ship to</p><p className="mt-3 font-semibold">{order.address?.address||"—"}</p><p className="mt-1 text-sm text-black/65">{order.address?`${order.address.city}, ${order.address.province} ${order.address.postal}`:"—"}</p></div></div>
   <div className="mt-8 overflow-hidden rounded-2xl border border-black/10"><table className="w-full border-collapse text-sm"><thead className="bg-[#171717] text-white"><tr><th className="px-5 py-4 text-left text-[10px] font-semibold uppercase tracking-[0.15em]">Item</th><th className="px-5 py-4 text-left text-[10px] font-semibold uppercase tracking-[0.15em]">Variant</th><th className="px-5 py-4 text-right text-[10px] font-semibold uppercase tracking-[0.15em]">Qty</th><th className="px-5 py-4 text-right text-[10px] font-semibold uppercase tracking-[0.15em]">Total</th></tr></thead><tbody>{order.items.map(item=><tr key={item.id} className="border-t border-black/10"><td className="px-5 py-4 font-medium">{item.product.name}</td><td className="px-5 py-4 text-black/55">{item.variant?`${item.variant.color} / ${item.variant.size}`:"—"}</td><td className="px-5 py-4 text-right">{item.quantity}</td><td className="px-5 py-4 text-right font-medium">{money(item.total)}</td></tr>)}</tbody></table></div>
   {!packing&&<div className="mt-7 grid gap-6 md:grid-cols-[1fr_280px]"><div className="rounded-2xl bg-[#faf9f6] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-black/45">Payment & fulfilment</p><p className="mt-3 text-sm font-medium">Payment: {order.paymentMethod==="COD"?"Cash on Delivery":order.paymentMethod}</p><p className="mt-1 text-sm text-black/65">Status: {order.status.replaceAll("_"," ")}</p>{order.trackingNumber&&<p className="mt-1 text-sm text-black/65">Tracking: {order.courier?`${order.courier} · `:""}{order.trackingNumber}</p>}</div><div className="rounded-2xl border border-black/10 p-5 text-sm"><div className="flex justify-between"><span className="text-black/55">Subtotal</span><span>{money(order.subtotal)}</span></div><div className="mt-2 flex justify-between"><span className="text-black/55">Discount</span><span>- {money(order.discount)}</span></div><div className="mt-2 flex justify-between"><span className="text-black/55">Shipping</span><span>{money(order.shipping)}</span></div><div className="mt-4 flex justify-between border-t border-black/10 pt-4 text-lg font-semibold"><span>Total</span><span>{money(order.total)}</span></div></div></div>}
   <div className="mt-9 flex flex-col items-center justify-between gap-6 border-t border-black/10 pt-7 sm:flex-row"><div><p className="font-editorial text-2xl">Made for your next occasion.</p><p className="mt-1 max-w-md text-xs leading-5 text-black/55">Visit NOORÉ for new arrivals, seasonal edits and premium Pakistani fashion.</p><p className="mt-2 text-xs font-medium">{site}</p></div><div className="text-center"><img src="/noore-website-qr.png" alt="Visit NOORÉ" className="h-24 w-24 rounded-xl border border-black/10 p-1"/><p className="mt-2 text-[9px] font-semibold uppercase tracking-[0.15em] text-black/45">Scan to visit NOORÉ</p></div></div>
   <p className="mt-7 text-center text-[9px] uppercase tracking-[0.18em] text-black/35">NOORÉ · Premium Pakistani fashion · Cash on Delivery</p>
  </div></div><script dangerouslySetInnerHTML={{__html:`window.addEventListener('load',()=>setTimeout(()=>window.print(),350))`}}/></main>
}
