import { notFound } from "next/navigation"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function PrintOrderPage({ params, searchParams }: { params: { id: string }; searchParams?: { mode?: string } }) {
  const order = await prisma.order.findUnique({ where: { id: params.id }, include: { user: { select: { name: true, email: true } }, address: true, items: { include: { product: true, variant: true } } } })
  if (!order) notFound()
  const packing = searchParams?.mode === "packing"
  return <main className="min-h-screen bg-white text-black p-8 print:p-0"><div className="max-w-3xl mx-auto"><div className="flex justify-between border-b pb-6 mb-6"><div><p className="text-2xl font-semibold tracking-[0.18em]">NOORÉ</p><p className="text-sm text-gray-500 mt-1">{packing ? "Packing slip" : "Order invoice"}</p></div><div className="text-right"><p className="font-semibold">#{order.orderNumber}</p><p className="text-sm text-gray-500">{order.createdAt.toLocaleString()}</p></div></div><div className="grid grid-cols-2 gap-8 mb-8 text-sm"><div><p className="text-gray-500 uppercase tracking-wider text-xs">Customer</p><p className="font-medium mt-1">{order.user?.name || "Customer"}</p><p>{order.user?.email || ""}</p><p>{order.address.phone}</p></div><div><p className="text-gray-500 uppercase tracking-wider text-xs">Ship to</p><p className="font-medium mt-1">{order.address.address}</p><p>{order.address.city}, {order.address.province} {order.address.postal}</p></div></div><table className="w-full text-sm border-collapse"><thead><tr className="border-y"><th className="text-left py-3">Item</th><th className="text-left py-3">Variant</th><th className="text-right py-3">Qty</th><th className="text-right py-3">Total</th></tr></thead><tbody>{order.items.map(item => <tr key={item.id} className="border-b"><td className="py-3">{item.product.name}</td><td className="py-3">{item.variant ? `${item.variant.color} / ${item.variant.size}` : "—"}</td><td className="text-right py-3">{item.quantity}</td><td className="text-right py-3">PKR {item.total.toLocaleString()}</td></tr>)}</tbody></table>{!packing && <><div className="ml-auto max-w-xs mt-6 space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>PKR {order.subtotal.toLocaleString()}</span></div><div className="flex justify-between"><span>Discount</span><span>- PKR {order.discount.toLocaleString()}</span></div><div className="flex justify-between"><span>Shipping</span><span>PKR {order.shipping.toLocaleString()}</span></div><div className="flex justify-between text-lg font-semibold border-t pt-3"><span>Total</span><span>PKR {order.total.toLocaleString()}</span></div></div><div className="mt-10 border-t pt-5 text-sm"><p className="font-medium">Payment: {order.paymentMethod === "COD" ? "Cash on Delivery" : order.paymentMethod}</p><p>Status: {order.status.replaceAll("_", " ")}</p>{order.trackingNumber && <p>Tracking: {order.courier ? `${order.courier} · ` : ""}{order.trackingNumber}</p>}</div></>}<script dangerouslySetInnerHTML={{__html:`window.addEventListener('load',()=>setTimeout(()=>window.print(),250))`}} /></div></main>
}
