"use client"
import { useEffect,useState } from "react"
type Section={id:string;type:string;enabled:boolean;sortOrder:number}
type Banner={id:string;heading:string;subtitle:string|null;image:string;mobileImage:string|null;video:string|null;buttonText:string|null;buttonUrl:string|null;active:boolean;sortOrder:number}
type BannerForm=Omit<Banner,"id"|"sortOrder">&{sortOrder:number}
const names:Record<string,string>={hero:"Hero Slider",categories:"Shop by Category",products:"New Arrivals",banner:"Collection Banner",luxury:"Luxury Edit",men:"Men's Edit",accessories:"Accessories",instagram:"Brand / Story",newsletter:"Newsletter"}
const emptyForm:BannerForm={heading:"",subtitle:"",image:"",mobileImage:"",video:"",buttonText:"Shop Now",buttonUrl:"/products",active:true,sortOrder:1}
export default function AdminHomepagePage(){
 const [sections,setSections]=useState<Section[]>([]),[banners,setBanners]=useState<Banner[]>([]),[form,setForm]=useState<BannerForm>(emptyForm),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("")
 const load=async()=>{const r=await fetch("/api/admin/homepage",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load homepage");setSections(d.sections);setBanners(d.banners)}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const toggle=(id:string)=>setSections(c=>c.map(s=>s.id===id?{...s,enabled:!s.enabled}:s))
 const move=(i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=sections.length)return;setSections(c=>{const n=[...c];[n[i],n[t]]=[n[t],n[i]];return n})}
 const saveLayout=async()=>{setSaving(true);setError("");setMessage("");try{const r=await fetch("/api/admin/homepage",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSections(d.sections);setMessage("Homepage layout saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save")}finally{setSaving(false)}}
 const saveBanner=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError("");setMessage("");try{const url=editing?`/api/admin/homepage/banners/${editing}`:"/api/admin/homepage/banners";const r=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setForm(emptyForm);setEditing(null);setMessage(editing?"Banner updated.":"Banner created.")}catch(e){setError(e instanceof Error?e.message:"Unable to save banner")}finally{setSaving(false)}}
 const editBanner=(b:Banner)=>{setEditing(b.id);setForm({...b,subtitle:b.subtitle||"",mobileImage:b.mobileImage||"",video:b.video||"",buttonText:b.buttonText||"",buttonUrl:b.buttonUrl||""});window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
 const deleteBanner=async(id:string)=>{if(!confirm("Delete this hero banner?"))return;const r=await fetch(`/api/admin/homepage/banners/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to delete banner");await load();setMessage("Banner deleted.")}
 if(loading)return <div className="max-w-7xl">{Header()}<div className="rounded-3xl border border-charcoal/10 bg-white p-12 text-center shadow-sm">Loading homepage builder…</div></div>
 return <div className="max-w-7xl pb-12">{Header()}<div className="space-y-5">
  <section className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><div className="flex flex-col gap-4 border-b border-charcoal/10 pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-secondary">01 / Storefront composition</p><h2 className="mt-2 text-xl font-semibold">Homepage sections</h2><p className="mt-1 text-sm text-secondary">Reorder and enable the same sections your storefront already uses.</p></div><button onClick={saveLayout} disabled={saving} className="rounded-xl bg-charcoal px-5 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white disabled:opacity-50">{saving?"Saving…":"Save Layout"}</button></div><div className="mt-5 space-y-2">{sections.map((s,i)=><div key={s.id} className="flex items-center gap-3 rounded-2xl border border-charcoal/10 bg-background p-3"><div className="flex gap-1"><button onClick={()=>move(i,-1)} disabled={i===0} className="grid h-9 w-9 place-items-center rounded-lg border border-charcoal/10 bg-white disabled:opacity-30">↑</button><button onClick={()=>move(i,1)} disabled={i===sections.length-1} className="grid h-9 w-9 place-items-center rounded-lg border border-charcoal/10 bg-white disabled:opacity-30">↓</button></div><div className="min-w-0 flex-1"><p className="font-medium">{names[s.type]||s.type}</p><p className="text-xs text-secondary">Position {i+1}</p></div><button onClick={()=>toggle(s.id)} className={`rounded-full border px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wide ${s.enabled?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-charcoal/10 bg-white text-secondary"}`}>{s.enabled?"Enabled":"Disabled"}</button></div>)}</div></section>
  <section className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><div className="flex flex-col gap-4 border-b border-charcoal/10 pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-secondary">02 / Campaign studio</p><h2 className="mt-2 text-xl font-semibold">Hero campaigns</h2><p className="mt-1 text-sm text-secondary">Manage the editorial banners shown on your storefront.</p></div><button onClick={()=>{setEditing(null);setForm({...emptyForm,sortOrder:banners.length+1})}} className="rounded-xl border border-charcoal/10 bg-white px-5 py-3 text-xs font-semibold uppercase tracking-[0.16em] shadow-sm">+ Add Banner</button></div>{banners.length===0?<div className="py-12 text-center text-sm text-secondary">No hero campaigns yet.</div>:<div className="mt-5 grid gap-4 md:grid-cols-2">{banners.map(b=><article key={b.id} className="overflow-hidden rounded-2xl border border-charcoal/10 bg-background"><img src={b.image} alt="" className="aspect-[16/7] w-full object-cover"/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{b.heading}</h3><p className="mt-1 text-xs text-secondary">{b.subtitle||"No subtitle"}</p></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase ${b.active?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-charcoal/10 bg-white text-secondary"}`}>{b.active?"Active":"Inactive"}</span></div><p className="mt-3 text-[10px] uppercase tracking-[0.16em] text-secondary">Display order {b.sortOrder}</p><div className="mt-4 flex gap-2"><button onClick={()=>editBanner(b)} className="rounded-lg border border-charcoal/10 bg-white px-3 py-2 text-xs font-medium">Edit</button><button onClick={()=>deleteBanner(b.id)} className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs font-medium text-red-600">Delete</button></div></div></article>)}</div>}</section>
  <form onSubmit={saveBanner} className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-secondary">03 / Campaign details</p><h2 className="mt-2 text-xl font-semibold">{editing?"Edit Hero Banner":"Create Hero Banner"}</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{([ ["heading","Heading"],["subtitle","Subtitle"],["image","Desktop Image URL"],["mobileImage","Mobile Image URL"],["buttonText","Button Text"],["buttonUrl","Button URL"],["video","Video URL"]] as const).map(([key,label])=><label key={key} className="text-sm"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.16em] text-secondary">{label}</span><input value={form[key]??""} onChange={e=>setForm(c=>({...c,[key]:e.target.value}))} className="w-full rounded-xl border border-charcoal/10 bg-background px-4 py-3 outline-none focus:border-charcoal" required={key==="heading"||key==="image"}/></label>)}<label className="text-sm"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.16em] text-secondary">Display order</span><input type="number" min="1" value={form.sortOrder} onChange={e=>setForm(c=>({...c,sortOrder:Number(e.target.value)}))} className="w-full rounded-xl border border-charcoal/10 bg-background px-4 py-3 outline-none focus:border-charcoal"/></label><label className="flex items-center gap-3 self-end rounded-xl border border-charcoal/10 bg-background px-4 py-3 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm(c=>({...c,active:e.target.checked}))}/><span>Active on storefront</span></label></div><div className="mt-6 flex flex-wrap gap-2"><button disabled={saving} className="rounded-xl bg-charcoal px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white disabled:opacity-50">{saving?"Saving…":editing?"Update Banner":"Create Banner"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(emptyForm)}} className="rounded-xl border border-charcoal/10 px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em]">Cancel</button>}</div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{message&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}</form>
 </div></div>
}
function Header(){return <header className="mb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-secondary">NOORÉ / Storefront</p><h1 className="mt-2 font-editorial text-4xl md:text-5xl">Homepage Builder</h1><p className="mt-2 max-w-3xl text-sm text-secondary">Shape the order, visibility and campaigns of the homepage without changing how the storefront works.</p></header>}
