"use client"

import { useEffect, useState } from "react"

type Courier = { id: string; name: string; accountNumber: string | null; contractNumber: string | null; contactName: string | null; contactPhone: string | null; contactEmail: string | null; pickupAddress: string | null; pickupCity: string | null; serviceNotes: string | null; apiBaseUrl: string | null; active: boolean }
const blank = { name: "", accountNumber: "", contractNumber: "", contactName: "", contactPhone: "", contactEmail: "", pickupAddress: "", pickupCity: "", serviceNotes: "", apiBaseUrl: "", apiKey: "", apiSecret: "", active: true }

export default function AdminCouriersPage() {
  const [couriers, setCouriers] = useState<Courier[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  async function load(){ setLoading(true); const r=await fetch("/api/admin/couriers",{cache:"no-store"}); const d=await r.json(); if(r.ok)setCouriers(d); else alert(d.error||"Failed to load couriers"); setLoading(false)}
  useEffect(()=>{load()},[])
  const update=(k:string,v:string|boolean)=>setForm(f=>({...f,[k]:v}))
  async function save(){ if(!form.name.trim())return; setSaving(true); const r=await fetch(editing?`/api/admin/couriers/${editing}`:"/api/admin/couriers",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json().catch(()=>({})); if(!r.ok)alert(d.error||"Could not save courier"); else {setForm(blank);setEditing(null);load()} setSaving(false)}
  async function remove(id:string){if(!confirm("Delete this courier company?"))return;const r=await fetch(`/api/admin/couriers/${id}`,{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok)alert(d.error||"Could not delete courier");else load()}
  function edit(c:Courier){setEditing(c.id);setForm({...blank,...c});window.scrollTo({top:0,behavior:"smooth"})}
  return <div className="max-w-6xl"><div className="mb-8"><p className="text-xs uppercase tracking-[0.22em] text-secondary">Operations</p><h1 className="mt-2 text-3xl font-semibold">Courier Companies</h1><p className="mt-2 text-sm text-secondary">Save your contracted courier profiles once. Orders can then use a saved courier instead of re-entering the company details every time.</p></div>
    <section className="bg-white rounded-xl border border-cream p-6 mb-6"><h2 className="text-lg font-semibold">{editing?"Edit courier contract":"Add courier company"}</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{[["name","Company name *"],["accountNumber","Account number"],["contractNumber","Contract number"],["contactName","Account/contact person"],["contactPhone","Contact phone"],["contactEmail","Contact email"],["pickupCity","Pickup city"],["apiBaseUrl","API base URL (optional)"],["apiKey","API key (optional)"],["apiSecret","API secret (optional)"]].map(([k,l])=><label key={k} className="text-sm font-medium">{l}<input type={k.includes("Email")?"email":"text"} value={(form as any)[k]} onChange={e=>update(k,e.target.value)} className="mt-1 w-full rounded border border-cream px-3 py-2" /></label>)}</div><label className="block text-sm font-medium mt-4">Pickup address<textarea rows={2} value={form.pickupAddress} onChange={e=>update("pickupAddress",e.target.value)} className="mt-1 w-full rounded border border-cream px-3 py-2"/></label><label className="block text-sm font-medium mt-4">Service notes<textarea rows={3} value={form.serviceNotes} onChange={e=>update("serviceNotes",e.target.value)} placeholder="Contract terms, COD notes, pickup schedule..." className="mt-1 w-full rounded border border-cream px-3 py-2"/></label><label className="flex items-center gap-2 text-sm mt-4"><input type="checkbox" checked={form.active} onChange={e=>update("active",e.target.checked)}/> Active courier</label><div className="flex gap-3 mt-5"><button onClick={save} disabled={saving||!form.name.trim()} className="rounded bg-charcoal px-6 py-2.5 text-sm text-white disabled:opacity-50">{saving?"Saving...":editing?"Save Courier":"Add Courier"}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(blank)}} className="rounded border border-cream px-6 py-2.5 text-sm">Cancel</button>}</div><p className="text-xs text-secondary mt-4">API credentials are optional profile fields for future courier API booking. This screen does not pretend to call a courier API unless that carrier integration is configured.</p></section>
    <section className="bg-white rounded-xl border border-cream overflow-hidden"><div className="p-5 border-b border-cream"><h2 className="font-semibold">Saved courier contracts</h2></div>{loading?<div className="p-8 text-secondary">Loading couriers...</div>:couriers.length===0?<div className="p-8 text-secondary">No courier companies configured yet.</div>:<div className="divide-y divide-cream">{couriers.map(c=><div key={c.id} className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><p className="font-semibold">{c.name}</p><span className={`text-xs px-2 py-1 rounded-full ${c.active?"bg-green-50 text-green-700":"bg-gray-100 text-gray-600"}`}>{c.active?"Active":"Disabled"}</span></div><p className="text-sm text-secondary mt-1">Account: {c.accountNumber||"—"} · Contract: {c.contractNumber||"—"}</p><p className="text-sm text-secondary">Pickup: {c.pickupCity||"—"} · Contact: {c.contactPhone||"—"}</p></div><div className="flex gap-2"><button onClick={()=>edit(c)} className="px-3 py-1.5 text-sm border border-cream rounded">Edit</button><button onClick={()=>remove(c.id)} className="px-3 py-1.5 text-sm border border-red-200 text-red-700 rounded">Delete</button></div></div>)}</div>}</section>
  </div>
}
