"use client"

import { useEffect, useState } from "react"
const defaults = { siteName:"NOORÉ", announcementText:"FREE SHIPPING ON ORDERS ABOVE PKR 5,000", freeShippingThreshold:"5000", standardShipping:"250", expressShipping:"500", currency:"PKR" }
type Settings=typeof defaults
export default function AdminSettingsPage(){
 const [settings,setSettings]=useState<Settings>(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("")
 useEffect(()=>{fetch("/api/admin/settings",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load settings");setSettings({...defaults,...d.settings})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const update=(key:keyof Settings,value:string)=>setSettings(c=>({...c,[key]:value}))
 const save=async()=>{setSaving(true);setMessage("");setError("");try{const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to save settings");setSettings({...defaults,...d.settings});setMessage("Settings saved successfully.")}catch(e){setError(e instanceof Error?e.message:"Failed to save settings")}finally{setSaving(false)}}
 const reset=()=>{setSettings(defaults);setMessage("");setError("")}
 if(loading)return <div className="max-w-6xl"><Header/><div className="rounded-3xl border border-charcoal/10 bg-white p-12 text-center shadow-sm">Loading store controls…</div></div>
 return <div className="max-w-6xl pb-12"><Header/><div className="space-y-5">
  <section className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><SectionTitle title="Store identity" text="Core storefront information and display currency."/><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Site name" value={settings.siteName} onChange={v=>update("siteName",v)}/><label className="text-sm"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.16em] text-secondary">Currency</span><select value={settings.currency} onChange={e=>update("currency",e.target.value)} className="w-full rounded-xl border border-charcoal/10 bg-background px-4 py-3 outline-none focus:border-charcoal"><option value="PKR">PKR — Pakistani Rupee</option><option value="USD">USD — US Dollar</option></select></label></div></section>
  <section className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><SectionTitle title="Announcement bar" text="The message shown across the storefront."/><div className="mt-6"><Field label="Announcement text" value={settings.announcementText} onChange={v=>update("announcementText",v)}/></div></section>
  <section className="rounded-3xl border border-charcoal/10 bg-white p-6 shadow-[0_12px_40px_rgba(23,23,23,0.05)]"><SectionTitle title="Shipping" text="Control free-shipping thresholds and delivery pricing."/><div className="mt-6 grid gap-5 md:grid-cols-3"><Field label="Free shipping threshold" type="number" value={settings.freeShippingThreshold} onChange={v=>update("freeShippingThreshold",v)}/><Field label="Standard shipping (PKR)" type="number" value={settings.standardShipping} onChange={v=>update("standardShipping",v)}/><Field label="Express shipping (PKR)" type="number" value={settings.expressShipping} onChange={v=>update("expressShipping",v)}/></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm text-emerald-700">{message}</div>}
  <div className="flex flex-wrap gap-3"><button onClick={save} disabled={saving} className="rounded-xl bg-charcoal px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white shadow-lg disabled:opacity-50">{saving?"Saving…":"Save Settings"}</button><button onClick={reset} disabled={saving} className="rounded-xl border border-charcoal/10 bg-white px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] shadow-sm disabled:opacity-50">Reset Form</button></div>
 </div></div>
}
function Header(){return <header className="mb-8"><p className="text-[10px] font-semibold uppercase tracking-[0.28em] text-secondary">NOORÉ / Configuration</p><h1 className="mt-2 font-editorial text-4xl md:text-5xl">Settings</h1><p className="mt-2 max-w-2xl text-sm text-secondary">A refined control room for store identity, announcements and delivery pricing.</p></header>}
function SectionTitle({title,text}:{title:string;text:string}){return <div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-secondary">{text}</p></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.16em] text-secondary">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} min={type==="number"?0:undefined} className="w-full rounded-xl border border-charcoal/10 bg-background px-4 py-3 outline-none transition focus:border-charcoal focus:ring-2 focus:ring-charcoal/5"/></label>}
