"use client"

import { useEffect, useState } from "react"

type Section = { id: string; type: string; enabled: boolean; sortOrder: number }
type Banner = { id: string; heading: string; subtitle: string | null; image: string; mobileImage: string | null; video: string | null; buttonText: string | null; buttonUrl: string | null; active: boolean; sortOrder: number }
type BannerForm = Omit<Banner, "id" | "sortOrder"> & { sortOrder: number }

const names: Record<string, string> = { hero: "Hero Slider", categories: "Shop by Category", products: "New Arrivals", banner: "Collection Banner", luxury: "Luxury Edit", men: "Men's Edit", accessories: "Accessories", instagram: "Brand / Story", newsletter: "Newsletter" }
const emptyForm: BannerForm = { heading: "", subtitle: "", image: "", mobileImage: "", video: "", buttonText: "Shop Now", buttonUrl: "/products", active: true, sortOrder: 1 }

export default function AdminHomepagePage() {
  const [sections, setSections] = useState<Section[]>([]); const [banners, setBanners] = useState<Banner[]>([]); const [form, setForm] = useState<BannerForm>(emptyForm); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  const load = async () => { const response = await fetch("/api/admin/homepage", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Failed to load homepage"); setSections(data.sections); setBanners(data.banners) }
  useEffect(() => { load().catch(err => setError(err.message)).finally(() => setLoading(false)) }, [])
  const toggle = (id: string) => setSections(current => current.map(s => s.id === id ? { ...s, enabled: !s.enabled } : s))
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= sections.length) return; setSections(current => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next }) }
  const saveLayout = async () => { setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/homepage", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sections }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSections(data.sections); setMessage("Homepage layout saved.") } catch (err) { setError(err instanceof Error ? err.message : "Unable to save") } finally { setSaving(false) } }
  const saveBanner = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const url = editing ? `/api/admin/homepage/banners/${editing}` : "/api/admin/homepage/banners"; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); setForm(emptyForm); setEditing(null); setMessage(editing ? "Banner updated." : "Banner created.") } catch (err) { setError(err instanceof Error ? err.message : "Unable to save banner") } finally { setSaving(false) } }
  const editBanner = (banner: Banner) => { setEditing(banner.id); setForm({ ...banner, subtitle: banner.subtitle || "", mobileImage: banner.mobileImage || "", video: banner.video || "", buttonText: banner.buttonText || "", buttonUrl: banner.buttonUrl || "" }); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }) }
  const deleteBanner = async (id: string) => { if (!confirm("Delete this hero banner?")) return; const response = await fetch(`/api/admin/homepage/banners/${id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setError(data.error || "Unable to delete banner"); await load(); setMessage("Banner deleted.") }
  if (loading) return <div className="max-w-5xl">Loading homepage...</div>
  return <div className="max-w-6xl pb-12"><h1 className="text-3xl font-semibold mb-2">Homepage Builder</h1><p className="text-secondary mb-8">Build a premium fashion marketplace-style homepage. Control the section order, visibility and hero campaigns.</p>
    <div className="bg-white rounded-lg border border-cream p-6"><div className="space-y-3">{sections.map((section, index) => <div key={section.id} className="flex items-center justify-between gap-4 p-4 border border-cream rounded-lg"><div className="flex items-center gap-4"><div className="flex flex-col gap-1"><button onClick={() => move(index, -1)} disabled={index === 0} className="text-xs border rounded px-2 py-0.5 disabled:opacity-30">↑</button><button onClick={() => move(index, 1)} disabled={index === sections.length - 1} className="text-xs border rounded px-2 py-0.5 disabled:opacity-30">↓</button></div><div><div className="font-medium">{names[section.type] || section.type}</div><div className="text-xs text-secondary">Position {index + 1}</div></div></div><button onClick={() => toggle(section.id)} className={`px-3 py-1 rounded text-sm ${section.enabled ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-700"}`}>{section.enabled ? "Enabled" : "Disabled"}</button></div>)}</div><button onClick={saveLayout} disabled={saving} className="mt-6 bg-charcoal text-white px-6 py-2 rounded disabled:opacity-50">{saving ? "Saving..." : "Save Layout"}</button></div>
    <div className="bg-white rounded-lg border border-cream p-6 mt-6"><div className="flex justify-between items-center mb-4"><div><h2 className="text-xl font-semibold">Hero Campaigns</h2><p className="text-sm text-secondary">Use large editorial imagery like the leading Pakistani fashion marketplaces.</p></div><button onClick={() => { setEditing(null); setForm({ ...emptyForm, sortOrder: banners.length + 1 }) }} className="border border-charcoal px-4 py-2 text-sm">+ Add Banner</button></div>{banners.length === 0 ? <p className="text-sm text-secondary">No banners yet. Add your first campaign below.</p> : <div className="grid gap-4 md:grid-cols-2">{banners.map(banner => <div key={banner.id} className="border border-cream overflow-hidden"><img src={banner.image} alt="" className="w-full aspect-[16/7] object-cover"/><div className="p-4"><div className="font-medium">{banner.heading}</div><div className="text-xs text-secondary mt-1">{banner.active ? "Active" : "Inactive"} · Order {banner.sortOrder}</div><div className="flex gap-2 mt-3"><button onClick={() => editBanner(banner)} className="text-xs border px-3 py-1">Edit</button><button onClick={() => deleteBanner(banner.id)} className="text-xs border px-3 py-1 text-red-600">Delete</button></div></div></div>)}</div>}</div>
    <form onSubmit={saveBanner} className="bg-white rounded-lg border border-cream p-6 mt-6"><h2 className="text-xl font-semibold mb-5">{editing ? "Edit Hero Banner" : "Add Hero Banner"}</h2><div className="grid md:grid-cols-2 gap-4">{([["heading","Heading"],["subtitle","Subtitle"],["image","Desktop Image URL"],["mobileImage","Mobile Image URL"],["buttonText","Button Text"],["buttonUrl","Button URL"],["video","Video URL"]] as const).map(([key,label]) => <label key={key} className="text-sm"><span className="block mb-1 font-medium">{label}</span><input value={form[key]} onChange={e => setForm(current => ({ ...current, [key]: e.target.value }))} className="w-full border border-cream rounded px-3 py-2 outline-none focus:border-charcoal" placeholder={key === "image" ? "https://..." : ""} required={key === "heading" || key === "image"}/></label>)}<label className="text-sm"><span className="block mb-1 font-medium">Display Order</span><input type="number" min="1" value={form.sortOrder} onChange={e => setForm(current => ({ ...current, sortOrder: Number(e.target.value) }))} className="w-full border border-cream rounded px-3 py-2"/></label><label className="flex items-center gap-2 text-sm mt-6"><input type="checkbox" checked={form.active} onChange={e => setForm(current => ({ ...current, active: e.target.checked }))}/> Active on storefront</label></div><div className="flex gap-2 mt-6"><button disabled={saving} className="bg-charcoal text-white px-6 py-2 rounded disabled:opacity-50">{saving ? "Saving..." : editing ? "Update Banner" : "Create Banner"}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(emptyForm) }} className="border px-6 py-2 rounded">Cancel</button>}</div>{error && <div className="mt-4 bg-red-50 text-red-700 px-4 py-3 text-sm">{error}</div>}{message && <div className="mt-4 bg-green-50 text-green-700 px-4 py-3 text-sm">{message}</div>}</form>
  </div>
}
