"use client"

import { useEffect, useState } from "react"

type Section = { id: string; type: string; enabled: boolean; sortOrder: number }
type Banner = { id: string; heading: string; subtitle: string | null; image: string; mobileImage: string | null; video: string | null; buttonText: string | null; buttonUrl: string | null; active: boolean; sortOrder: number }
type BannerForm = Omit<Banner, "id" | "sortOrder"> & { sortOrder: number }

const names: Record<string, string> = { hero: "Hero Slider", categories: "Shop by Category", products: "New Arrivals", banner: "Collection Banner", luxury: "Luxury Edit", men: "Men's Edit", accessories: "Accessories", instagram: "Brand / Story", newsletter: "Newsletter" }
const emptyForm: BannerForm = { heading: "", subtitle: "", image: "", mobileImage: "", video: "", buttonText: "Shop Now", buttonUrl: "/products", active: true, sortOrder: 1 }

export default function AdminHomepagePage() {
  const [sections, setSections] = useState<Section[]>([]); const [banners, setBanners] = useState<Banner[]>([]); const [form, setForm] = useState<BannerForm>(emptyForm); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  const load = async () => { const response = await fetch("/api/admin/homepage", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Failed to load homepage"); setSections(data.sections); setBanners(data.banners) }
  useEffect(() => { load().catch(err => setError(err.message)).finally(() => setLoading(false)) }, [])
  const toggle = (id: string) => setSections(current => current.map(s => s.id === id ? { ...s, enabled: !s.enabled } : s))
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= sections.length) return; setSections(current => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next }) }
  const saveLayout = async () => { setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/homepage", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sections }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSections(data.sections); setMessage("Homepage layout saved.") } catch (err) { setError(err instanceof Error ? err.message : "Unable to save") } finally { setSaving(false) } }
  const saveBanner = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const url = editing ? `/api/admin/homepage/banners/${editing}` : "/api/admin/homepage/banners"; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); setForm(emptyForm); setEditing(null); setMessage(editing ? "Banner updated." : "Banner created.") } catch (err) { setError(err instanceof Error ? err.message : "Unable to save banner") } finally { setSaving(false) } }
  const editBanner = (banner: Banner) => { setEditing(banner.id); setForm({ ...banner, subtitle: banner.subtitle || "", mobileImage: banner.mobileImage || "", video: banner.video || "", buttonText: banner.buttonText || "", buttonUrl: banner.buttonUrl || "" }); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }) }
  const deleteBanner = async (id: string) => { if (!confirm("Delete this hero banner?")) return; const response = await fetch(`/api/admin/homepage/banners/${id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setError(data.error || "Unable to delete banner"); await load(); setMessage("Banner deleted.") }
  if (loading) return <div className="admin-page admin-surface flex min-h-56 items-center justify-center"><div className="text-center"><div className="mx-auto h-8 w-8 animate-spin rounded-full border-2 border-white/15 border-t-white"/><p className="mt-4 text-sm text-white/50">Loading homepage builder…</p></div></div>
  return <div className="admin-page space-y-7 pb-12">
    <header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="admin-eyebrow">Content / Storefront</p><h1 className="admin-title">Homepage Builder</h1><p className="admin-subtitle">Arrange storefront sections and manage hero campaigns with the same controls as before.</p></div><span className="hidden rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-xs text-white/50 md:block">Live storefront controls</span></header>
    <section className="admin-surface"><div className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-base font-semibold text-white">Section order</h2><p className="mt-1 text-sm text-white/45">Move sections up or down and toggle visibility.</p></div><button onClick={saveLayout} disabled={saving} className="admin-button-primary w-fit">{saving?"Saving…":"Save layout"}</button></div><div className="space-y-2">{sections.map((section,index)=><div key={section.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/[0.08] bg-white/[0.025] p-3.5 transition hover:border-white/15"><div className="flex min-w-0 items-center gap-3"><div className="flex flex-col gap-1"><button aria-label="Move up" onClick={()=>move(index,-1)} disabled={index===0} className="grid h-7 w-7 place-items-center rounded-lg border border-white/10 text-xs text-white/60 disabled:opacity-20">↑</button><button aria-label="Move down" onClick={()=>move(index,1)} disabled={index===sections.length-1} className="grid h-7 w-7 place-items-center rounded-lg border border-white/10 text-xs text-white/60 disabled:opacity-20">↓</button></div><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{names[section.type]||section.type}</p><p className="mt-1 text-xs text-white/35">Position {index+1}</p></div></div><button onClick={()=>toggle(section.id)} className={`shrink-0 rounded-full border px-3 py-1.5 text-[11px] font-medium ${section.enabled?"border-emerald-400/20 bg-emerald-400/10 text-emerald-200":"border-white/10 bg-white/[0.04] text-white/45"}`}>{section.enabled?"Enabled":"Disabled"}</button></div>)}</div></section>
    <section className="admin-surface"><div className="flex flex-col gap-4 border-b border-white/10 pb-5 md:flex-row md:items-end md:justify-between"><div><h2 className="text-base font-semibold text-white">Hero campaigns</h2><p className="mt-1 text-sm text-white/45">Large editorial banners used on the storefront.</p></div><button onClick={()=>{setEditing(null);setForm({...emptyForm,sortOrder:banners.length+1})}} className="admin-button-secondary w-fit">+ Add banner</button></div>{banners.length===0?<div className="py-12 text-center"><p className="font-medium text-white">No hero campaigns yet</p><p className="mt-1 text-sm text-white/40">Add your first campaign below.</p></div>:<div className="mt-5 grid gap-4 lg:grid-cols-2">{banners.map(banner=><article key={banner.id} className="overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.025]"><img src={banner.image} alt="" className="aspect-[16/7] w-full object-cover"/><div className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-white">{banner.heading}</p><p className="mt-1 text-xs text-white/40">{banner.active?"Active":"Inactive"} · Order {banner.sortOrder}</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] uppercase tracking-[0.12em] text-white/40">Hero</span></div><div className="mt-4 flex gap-2"><button onClick={()=>editBanner(banner)} className="admin-button-secondary !px-3 !py-2 text-xs">Edit</button><button onClick={()=>deleteBanner(banner.id)} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300 hover:bg-red-400/10">Delete</button></div></div></article>)}</div>}</section>
    <form onSubmit={saveBanner} className="admin-surface"><div className="mb-5"><p className="admin-eyebrow">Campaign editor</p><h2 className="mt-2 text-base font-semibold text-white">{editing?"Edit hero banner":"Add hero banner"}</h2><p className="mt-1 text-sm text-white/45">Keep your existing banner fields and publishing controls.</p></div><div className="grid gap-4 md:grid-cols-2">{([["heading","Heading"],["subtitle","Subtitle"],["image","Desktop Image URL"],["mobileImage","Mobile Image URL"],["buttonText","Button Text"],["buttonUrl","Button URL"],["video","Video URL"]] as const).map(([key,label])=><label key={key} className="block text-sm"><span className="mb-2 block text-xs font-medium uppercase tracking-[0.12em] text-white/45">{label}</span><input value={form[key]??""} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))} className="admin-input" placeholder={key==="image"?"https://…":""} required={key==="heading"||key==="image"}/></label>)}<label className="block text-sm"><span className="mb-2 block text-xs font-medium uppercase tracking-[0.12em] text-white/45">Display order</span><input type="number" min="1" value={form.sortOrder} onChange={e=>setForm(current=>({...current,sortOrder:Number(e.target.value)}))} className="admin-input"/></label><label className="flex items-center gap-3 rounded-xl border border-white/[0.08] bg-white/[0.025] px-4 py-3 text-sm text-white/70"><input type="checkbox" checked={form.active} onChange={e=>setForm(current=>({...current,active:e.target.checked}))} className="h-4 w-4 accent-white"/> Active on storefront</label></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={saving} className="admin-button-primary">{saving?"Saving…":editing?"Update banner":"Create banner"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(emptyForm)}} className="admin-button-secondary">Cancel</button>}</div>{error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}{message&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">{message}</div>}</form>
  </div>
}
